<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $query = "INSERT INTO cities (id, state_id, name, is_capital)
                  OVERRIDING SYSTEM VALUE
                  VALUES (1, 1, 'Maroa', FALSE),
                         (2, 1, 'Puerto Ayacucho', TRUE),
                         (3, 1, 'San Fernando de Atabapo', FALSE),
                         (4, 2, 'Anaco', FALSE),
                         (5, 2, 'Aragua de Barcelona', FALSE),
                         (6, 2, 'Barcelona', TRUE),
                         (7, 2, 'Boca de Uchire', FALSE),
                         (8, 2, 'Cantaura', FALSE),
                         (9, 2, 'Clarines', FALSE),
                         (10, 2, 'El Chaparro', FALSE),
                         (11, 2, 'El Pao Anzoátegui', FALSE),
                         (12, 2, 'El Tigre', FALSE),
                         (13, 2, 'El Tigrito', FALSE),
                         (14, 2, 'Guanape', FALSE),
                         (15, 2, 'Guanta', FALSE),
                         (16, 2, 'Lechería', FALSE),
                         (17, 2, 'Onoto', FALSE),
                         (18, 2, 'Pariaguán', FALSE),
                         (19, 2, 'Píritu', FALSE),
                         (20, 2, 'Puerto La Cruz', FALSE),
                         (21, 2, 'Puerto Píritu', FALSE),
                         (22, 2, 'Sabana de Uchire', FALSE),
                         (23, 2, 'San Mateo Anzoátegui', FALSE),
                         (24, 2, 'San Pablo Anzoátegui', FALSE),
                         (25, 2, 'San Tomé', FALSE),
                         (26, 2, 'Santa Ana de Anzoátegui', FALSE),
                         (27, 2, 'Santa Fe Anzoátegui', FALSE),
                         (28, 2, 'Santa Rosa', FALSE),
                         (29, 2, 'Soledad', FALSE),
                         (30, 2, 'Urica', FALSE),
                         (31, 2, 'Valle de Guanape', FALSE),
                         (43, 3, 'Achaguas', FALSE),
                         (44, 3, 'Biruaca', FALSE),
                         (45, 3, 'Bruzual', FALSE),
                         (46, 3, 'El Amparo', FALSE),
                         (47, 3, 'El Nula', FALSE),
                         (48, 3, 'Elorza', FALSE),
                         (49, 3, 'Guasdualito', FALSE),
                         (50, 3, 'Mantecal', FALSE),
                         (51, 3, 'Puerto Páez', FALSE),
                         (52, 3, 'San Fernando de Apure', TRUE),
                         (53, 3, 'San Juan de Payara', FALSE),
                         (54, 4, 'Barbacoas', FALSE),
                         (55, 4, 'Cagua', FALSE),
                         (56, 4, 'Camatagua', FALSE),
                         (58, 4, 'Choroní', FALSE),
                         (59, 4, 'Colonia Tovar', FALSE),
                         (60, 4, 'El Consejo', FALSE),
                         (61, 4, 'La Victoria', FALSE),
                         (62, 4, 'Las Tejerías', FALSE),
                         (63, 4, 'Magdaleno', FALSE),
                         (64, 4, 'Maracay', TRUE),
                         (65, 4, 'Ocumare de La Costa', FALSE),
                         (66, 4, 'Palo Negro', FALSE),
                         (67, 4, 'San Casimiro', FALSE),
                         (68, 4, 'San Mateo', FALSE),
                         (69, 4, 'San Sebastián', FALSE),
                         (70, 4, 'Santa Cruz de Aragua', FALSE),
                         (71, 4, 'Tocorón', FALSE),
                         (72, 4, 'Turmero', FALSE),
                         (73, 4, 'Villa de Cura', FALSE),
                         (74, 4, 'Zuata', FALSE),
                         (75, 5, 'Barinas', TRUE),
                         (76, 5, 'Barinitas', FALSE),
                         (77, 5, 'Barrancas', FALSE),
                         (78, 5, 'Calderas', FALSE),
                         (79, 5, 'Capitanejo', FALSE),
                         (80, 5, 'Ciudad Bolivia', FALSE),
                         (81, 5, 'El Cantón', FALSE),
                         (82, 5, 'Las Veguitas', FALSE),
                         (83, 5, 'Libertad de Barinas', FALSE),
                         (84, 5, 'Sabaneta', FALSE),
                         (85, 5, 'Santa Bárbara de Barinas', FALSE),
                         (86, 5, 'Socopó', FALSE),
                         (87, 6, 'Caicara del Orinoco', FALSE),
                         (88, 6, 'Canaima', FALSE),
                         (89, 6, 'Ciudad Bolívar', TRUE),
                         (90, 6, 'Ciudad Piar', FALSE),
                         (91, 6, 'El Callao', FALSE),
                         (92, 6, 'El Dorado', FALSE),
                         (93, 6, 'El Manteco', FALSE),
                         (94, 6, 'El Palmar', FALSE),
                         (95, 6, 'El Pao', FALSE),
                         (96, 6, 'Guasipati', FALSE),
                         (97, 6, 'Guri', FALSE),
                         (98, 6, 'La Paragua', FALSE),
                         (99, 6, 'Matanzas', FALSE),
                         (100, 6, 'Puerto Ordaz', FALSE),
                         (101, 6, 'San Félix', FALSE),
                         (102, 6, 'Santa Elena de Uairén', FALSE),
                         (103, 6, 'Tumeremo', FALSE),
                         (104, 6, 'Unare', FALSE),
                         (105, 6, 'Upata', FALSE),
                         (106, 7, 'Bejuma', FALSE),
                         (107, 7, 'Belén', FALSE),
                         (108, 7, 'Campo de Carabobo', FALSE),
                         (109, 7, 'Canoabo', FALSE),
                         (110, 7, 'Central Tacarigua', FALSE),
                         (111, 7, 'Chirgua', FALSE),
                         (112, 7, 'Ciudad Alianza', FALSE),
                         (113, 7, 'El Palito', FALSE),
                         (114, 7, 'Guacara', FALSE),
                         (115, 7, 'Guigue', FALSE),
                         (116, 7, 'Las Trincheras', FALSE),
                         (117, 7, 'Los Guayos', FALSE),
                         (118, 7, 'Mariara', FALSE),
                         (119, 7, 'Miranda', FALSE),
                         (120, 7, 'Montalbán', FALSE),
                         (121, 7, 'Morón', FALSE),
                         (122, 7, 'Naguanagua', FALSE),
                         (123, 7, 'Puerto Cabello', FALSE),
                         (124, 7, 'San Joaquín', FALSE),
                         (125, 7, 'Tocuyito', FALSE),
                         (126, 7, 'Urama', FALSE),
                         (127, 7, 'Valencia', TRUE),
                         (128, 7, 'Vigirimita', FALSE),
                         (129, 8, 'Aguirre', FALSE),
                         (130, 8, 'Apartaderos Cojedes', FALSE),
                         (131, 8, 'Arismendi', FALSE),
                         (132, 8, 'Camuriquito', FALSE),
                         (133, 8, 'El Baúl', FALSE),
                         (134, 8, 'El Limón', FALSE),
                         (135, 8, 'El Pao Cojedes', FALSE),
                         (136, 8, 'El Socorro', FALSE),
                         (137, 8, 'La Aguadita', FALSE),
                         (138, 8, 'Las Vegas', FALSE),
                         (139, 8, 'Libertad de Cojedes', FALSE),
                         (140, 8, 'Mapuey', FALSE),
                         (141, 8, 'Piñedo', FALSE),
                         (142, 8, 'Samancito', FALSE),
                         (143, 8, 'San Carlos', TRUE),
                         (144, 8, 'Sucre', FALSE),
                         (145, 8, 'Tinaco', FALSE),
                         (146, 8, 'Tinaquillo', FALSE),
                         (147, 8, 'Vallecito', FALSE),
                         (148, 9, 'Tucupita', TRUE),
                         (149, 24, 'Caracas', TRUE),
                         (150, 24, 'El Junquito', FALSE),
                         (151, 10, 'Adícora', FALSE),
                         (152, 10, 'Boca de Aroa', FALSE),
                         (153, 10, 'Cabure', FALSE),
                         (154, 10, 'Capadare', FALSE),
                         (155, 10, 'Capatárida', FALSE),
                         (156, 10, 'Chichiriviche', FALSE),
                         (157, 10, 'Churuguara', FALSE),
                         (158, 10, 'Coro', TRUE),
                         (159, 10, 'Cumarebo', FALSE),
                         (160, 10, 'Dabajuro', FALSE),
                         (161, 10, 'Judibana', FALSE),
                         (162, 10, 'La Cruz de Taratara', FALSE),
                         (163, 10, 'La Vela de Coro', FALSE),
                         (164, 10, 'Los Taques', FALSE),
                         (165, 10, 'Maparari', FALSE),
                         (166, 10, 'Mene de Mauroa', FALSE),
                         (167, 10, 'Mirimire', FALSE),
                         (168, 10, 'Pedregal', FALSE),
                         (169, 10, 'Píritu Falcón', FALSE),
                         (170, 10, 'Pueblo Nuevo Falcón', FALSE),
                         (171, 10, 'Puerto Cumarebo', FALSE),
                         (172, 10, 'Punta Cardón', FALSE),
                         (173, 10, 'Punto Fijo', FALSE),
                         (174, 10, 'San Juan de Los Cayos', FALSE),
                         (175, 10, 'San Luis', FALSE),
                         (176, 10, 'Santa Ana Falcón', FALSE),
                         (177, 10, 'Santa Cruz De Bucaral', FALSE),
                         (178, 10, 'Tocopero', FALSE),
                         (179, 10, 'Tocuyo de La Costa', FALSE),
                         (180, 10, 'Tucacas', FALSE),
                         (181, 10, 'Yaracal', FALSE),
                         (182, 11, 'Altagracia de Orituco', FALSE),
                         (183, 11, 'Cabruta', FALSE),
                         (184, 11, 'Calabozo', FALSE),
                         (185, 11, 'Camaguán', FALSE),
                         (196, 11, 'Chaguaramas Guárico', FALSE),
                         (197, 11, 'El Socorro', FALSE),
                         (198, 11, 'El Sombrero', FALSE),
                         (199, 11, 'Las Mercedes de Los Llanos', FALSE),
                         (200, 11, 'Lezama', FALSE),
                         (201, 11, 'Onoto', FALSE),
                         (202, 11, 'Ortíz', FALSE),
                         (203, 11, 'San José de Guaribe', FALSE),
                         (204, 11, 'San Juan de Los Morros', TRUE),
                         (205, 11, 'San Rafael de Laya', FALSE),
                         (206, 11, 'Santa María de Ipire', FALSE),
                         (207, 11, 'Tucupido', FALSE),
                         (208, 11, 'Valle de La Pascua', FALSE),
                         (209, 11, 'Zaraza', FALSE),
                         (210, 12, 'Aguada Grande', FALSE),
                         (211, 12, 'Atarigua', FALSE),
                         (212, 12, 'Barquisimeto', TRUE),
                         (213, 12, 'Bobare', FALSE),
                         (214, 12, 'Cabudare', FALSE),
                         (215, 12, 'Carora', FALSE),
                         (216, 12, 'Cubiro', FALSE),
                         (217, 12, 'Cují', FALSE),
                         (218, 12, 'Duaca', FALSE),
                         (219, 12, 'El Manzano', FALSE),
                         (220, 12, 'El Tocuyo', FALSE),
                         (221, 12, 'Guaríco', FALSE),
                         (222, 12, 'Humocaro Alto', FALSE),
                         (223, 12, 'Humocaro Bajo', FALSE),
                         (224, 12, 'La Miel', FALSE),
                         (225, 12, 'Moroturo', FALSE),
                         (226, 12, 'Quíbor', FALSE),
                         (227, 12, 'Río Claro', FALSE),
                         (228, 12, 'Sanare', FALSE),
                         (229, 12, 'Santa Inés', FALSE),
                         (230, 12, 'Sarare', FALSE),
                         (231, 12, 'Siquisique', FALSE),
                         (232, 12, 'Tintorero', FALSE),
                         (233, 13, 'Apartaderos Mérida', FALSE),
                         (234, 13, 'Arapuey', FALSE),
                         (235, 13, 'Bailadores', FALSE),
                         (236, 13, 'Caja Seca', FALSE),
                         (237, 13, 'Canaguá', FALSE),
                         (238, 13, 'Chachopo', FALSE),
                         (239, 13, 'Chiguara', FALSE),
                         (240, 13, 'Ejido', FALSE),
                         (241, 13, 'El Vigía', FALSE),
                         (242, 13, 'La Azulita', FALSE),
                         (243, 13, 'La Playa', FALSE),
                         (244, 13, 'Lagunillas Mérida', FALSE),
                         (245, 13, 'Mérida', TRUE),
                         (246, 13, 'Mesa de Bolívar', FALSE),
                         (247, 13, 'Mucuchíes', FALSE),
                         (248, 13, 'Mucujepe', FALSE),
                         (249, 13, 'Mucuruba', FALSE),
                         (250, 13, 'Nueva Bolivia', FALSE),
                         (251, 13, 'Palmarito', FALSE),
                         (252, 13, 'Pueblo Llano', FALSE),
                         (253, 13, 'Santa Cruz de Mora', FALSE),
                         (254, 13, 'Santa Elena de Arenales', FALSE),
                         (255, 13, 'Santo Domingo', FALSE),
                         (256, 13, 'Tabáy', FALSE),
                         (257, 13, 'Timotes', FALSE),
                         (258, 13, 'Torondoy', FALSE),
                         (259, 13, 'Tovar', FALSE),
                         (260, 13, 'Tucani', FALSE),
                         (261, 13, 'Zea', FALSE),
                         (262, 14, 'Araguita', FALSE),
                         (263, 14, 'Carrizal', FALSE),
                         (264, 14, 'Caucagua', FALSE),
                         (265, 14, 'Chaguaramas Miranda', FALSE),
                         (266, 14, 'Charallave', FALSE),
                         (267, 14, 'Chirimena', FALSE),
                         (268, 14, 'Chuspa', FALSE),
                         (269, 14, 'Cúa', FALSE),
                         (270, 14, 'Cupira', FALSE),
                         (271, 14, 'Curiepe', FALSE),
                         (272, 14, 'El Guapo', FALSE),
                         (273, 14, 'El Jarillo', FALSE),
                         (274, 14, 'Filas de Mariche', FALSE),
                         (275, 14, 'Guarenas', FALSE),
                         (276, 14, 'Guatire', FALSE),
                         (277, 14, 'Higuerote', FALSE),
                         (278, 14, 'Los Anaucos', FALSE),
                         (279, 14, 'Los Teques', TRUE),
                         (280, 14, 'Ocumare del Tuy', FALSE),
                         (281, 14, 'Panaquire', FALSE),
                         (282, 14, 'Paracotos', FALSE),
                         (283, 14, 'Río Chico', FALSE),
                         (284, 14, 'San Antonio de Los Altos', FALSE),
                         (285, 14, 'San Diego de Los Altos', FALSE),
                         (286, 14, 'San Fernando del Guapo', FALSE),
                         (287, 14, 'San Francisco de Yare', FALSE),
                         (288, 14, 'San José de Los Altos', FALSE),
                         (289, 14, 'San José de Río Chico', FALSE),
                         (290, 14, 'San Pedro de Los Altos', FALSE),
                         (291, 14, 'Santa Lucía', FALSE),
                         (292, 14, 'Santa Teresa', FALSE),
                         (293, 14, 'Tacarigua de La Laguna', FALSE),
                         (294, 14, 'Tacarigua de Mamporal', FALSE),
                         (295, 14, 'Tácata', FALSE),
                         (296, 14, 'Turumo', FALSE),
                         (297, 15, 'Aguasay', FALSE),
                         (298, 15, 'Aragua de Maturín', FALSE),
                         (299, 15, 'Barrancas del Orinoco', FALSE),
                         (300, 15, 'Caicara de Maturín', FALSE),
                         (301, 15, 'Caripe', FALSE),
                         (302, 15, 'Caripito', FALSE),
                         (303, 15, 'Chaguaramal', FALSE),
                         (305, 15, 'Chaguaramas Monagas', FALSE),
                         (307, 15, 'El Furrial', FALSE),
                         (308, 15, 'El Tejero', FALSE),
                         (309, 15, 'Jusepín', FALSE),
                         (310, 15, 'La Toscana', FALSE),
                         (311, 15, 'Maturín', TRUE),
                         (312, 15, 'Miraflores', FALSE),
                         (313, 15, 'Punta de Mata', FALSE),
                         (314, 15, 'Quiriquire', FALSE),
                         (315, 15, 'San Antonio de Maturín', FALSE),
                         (316, 15, 'San Vicente Monagas', FALSE),
                         (317, 15, 'Santa Bárbara', FALSE),
                         (318, 15, 'Temblador', FALSE),
                         (319, 15, 'Teresen', FALSE),
                         (320, 15, 'Uracoa', FALSE),
                         (321, 16, 'Altagracia', FALSE),
                         (322, 16, 'Boca de Pozo', FALSE),
                         (323, 16, 'Boca de Río', FALSE),
                         (324, 16, 'El Espinal', FALSE),
                         (325, 16, 'El Valle del Espíritu Santo', FALSE),
                         (326, 16, 'El Yaque', FALSE),
                         (327, 16, 'Juangriego', FALSE),
                         (328, 16, 'La Asunción', TRUE),
                         (329, 16, 'La Guardia', FALSE),
                         (330, 16, 'Pampatar', FALSE),
                         (331, 16, 'Porlamar', FALSE),
                         (332, 16, 'Puerto Fermín', FALSE),
                         (333, 16, 'Punta de Piedras', FALSE),
                         (334, 16, 'San Francisco de Macanao', FALSE),
                         (335, 16, 'San Juan Bautista', FALSE),
                         (336, 16, 'San Pedro de Coche', FALSE),
                         (337, 16, 'Santa Ana de Nueva Esparta', FALSE),
                         (338, 16, 'Villa Rosa', FALSE),
                         (339, 17, 'Acarigua', FALSE),
                         (340, 17, 'Agua Blanca', FALSE),
                         (341, 17, 'Araure', FALSE),
                         (342, 17, 'Biscucuy', FALSE),
                         (343, 17, 'Boconoito', FALSE),
                         (344, 17, 'Campo Elías', FALSE),
                         (345, 17, 'Chabasquén', FALSE),
                         (346, 17, 'Guanare', TRUE),
                         (347, 17, 'Guanarito', FALSE),
                         (348, 17, 'La Aparición', FALSE),
                         (349, 17, 'La Misión', FALSE),
                         (350, 17, 'Mesa de Cavacas', FALSE),
                         (351, 17, 'Ospino', FALSE),
                         (352, 17, 'Papelón', FALSE),
                         (353, 17, 'Payara', FALSE),
                         (354, 17, 'Pimpinela', FALSE),
                         (355, 17, 'Píritu de Portuguesa', FALSE),
                         (356, 17, 'San Rafael de Onoto', FALSE),
                         (357, 17, 'Santa Rosalía', FALSE),
                         (358, 17, 'Turén', FALSE),
                         (359, 18, 'Altos de Sucre', FALSE),
                         (360, 18, 'Araya', FALSE),
                         (361, 18, 'Cariaco', FALSE),
                         (362, 18, 'Carúpano', FALSE),
                         (363, 18, 'Casanay', FALSE),
                         (364, 18, 'Cumaná', TRUE),
                         (365, 18, 'Cumanacoa', FALSE),
                         (366, 18, 'El Morro Puerto Santo', FALSE),
                         (367, 18, 'El Pilar', FALSE),
                         (368, 18, 'El Poblado', FALSE),
                         (369, 18, 'Guaca', FALSE),
                         (370, 18, 'Guiria', FALSE),
                         (371, 18, 'Irapa', FALSE),
                         (372, 18, 'Manicuare', FALSE),
                         (373, 18, 'Mariguitar', FALSE),
                         (374, 18, 'Río Caribe', FALSE),
                         (375, 18, 'San Antonio del Golfo', FALSE),
                         (376, 18, 'San José de Aerocuar', FALSE),
                         (377, 18, 'San Vicente de Sucre', FALSE),
                         (378, 18, 'Santa Fe de Sucre', FALSE),
                         (379, 18, 'Tunapuy', FALSE),
                         (380, 18, 'Yaguaraparo', FALSE),
                         (381, 18, 'Yoco', FALSE),
                         (382, 19, 'Abejales', FALSE),
                         (383, 19, 'Borota', FALSE),
                         (384, 19, 'Bramon', FALSE),
                         (385, 19, 'Capacho', FALSE),
                         (386, 19, 'Colón', FALSE),
                         (387, 19, 'Coloncito', FALSE),
                         (388, 19, 'Cordero', FALSE),
                         (389, 19, 'El Cobre', FALSE),
                         (390, 19, 'El Pinal', FALSE),
                         (391, 19, 'Independencia', FALSE),
                         (392, 19, 'La Fría', FALSE),
                         (393, 19, 'La Grita', FALSE),
                         (394, 19, 'La Pedrera', FALSE),
                         (395, 19, 'La Tendida', FALSE),
                         (396, 19, 'Las Delicias', FALSE),
                         (397, 19, 'Las Hernández', FALSE),
                         (398, 19, 'Lobatera', FALSE),
                         (399, 19, 'Michelena', FALSE),
                         (400, 19, 'Palmira', FALSE),
                         (401, 19, 'Pregonero', FALSE),
                         (402, 19, 'Queniquea', FALSE),
                         (403, 19, 'Rubio', FALSE),
                         (404, 19, 'San Antonio del Tachira', FALSE),
                         (405, 19, 'San Cristobal', TRUE),
                         (406, 19, 'San José de Bolívar', FALSE),
                         (407, 19, 'San Josecito', FALSE),
                         (408, 19, 'San Pedro del Río', FALSE),
                         (409, 19, 'Santa Ana Táchira', FALSE),
                         (410, 19, 'Seboruco', FALSE),
                         (411, 19, 'Táriba', FALSE),
                         (412, 19, 'Umuquena', FALSE),
                         (413, 19, 'Ureña', FALSE),
                         (414, 20, 'Batatal', FALSE),
                         (415, 20, 'Betijoque', FALSE),
                         (416, 20, 'Boconó', FALSE),
                         (417, 20, 'Carache', FALSE),
                         (418, 20, 'Chejende', FALSE),
                         (419, 20, 'Cuicas', FALSE),
                         (420, 20, 'El Dividive', FALSE),
                         (421, 20, 'El Jaguito', FALSE),
                         (422, 20, 'Escuque', FALSE),
                         (423, 20, 'Isnotú', FALSE),
                         (424, 20, 'Jajó', FALSE),
                         (425, 20, 'La Ceiba', FALSE),
                         (426, 20, 'La Concepción de Trujllo', FALSE),
                         (427, 20, 'La Mesa de Esnujaque', FALSE),
                         (428, 20, 'La Puerta', FALSE),
                         (429, 20, 'La Quebrada', FALSE),
                         (430, 20, 'Mendoza Fría', FALSE),
                         (431, 20, 'Meseta de Chimpire', FALSE),
                         (432, 20, 'Monay', FALSE),
                         (433, 20, 'Motatán', FALSE),
                         (434, 20, 'Pampán', FALSE),
                         (435, 20, 'Pampanito', FALSE),
                         (436, 20, 'Sabana de Mendoza', FALSE),
                         (437, 20, 'San Lázaro', FALSE),
                         (438, 20, 'Santa Ana de Trujillo', FALSE),
                         (439, 20, 'Tostós', FALSE),
                         (440, 20, 'Trujillo', TRUE),
                         (441, 20, 'Valera', FALSE),
                         (442, 21, 'Carayaca', FALSE),
                         (443, 21, 'Litoral', FALSE),
                         (444, 25, 'Archipiélago Los Roques', FALSE),
                         (445, 22, 'Aroa', FALSE),
                         (446, 22, 'Boraure', FALSE),
                         (447, 22, 'Campo Elías de Yaracuy', FALSE),
                         (448, 22, 'Chivacoa', FALSE),
                         (449, 22, 'Cocorote', FALSE),
                         (450, 22, 'Farriar', FALSE),
                         (451, 22, 'Guama', FALSE),
                         (452, 22, 'Marín', FALSE),
                         (453, 22, 'Nirgua', FALSE),
                         (454, 22, 'Sabana de Parra', FALSE),
                         (455, 22, 'Salom', FALSE),
                         (456, 22, 'San Felipe', TRUE),
                         (457, 22, 'San Pablo de Yaracuy', FALSE),
                         (458, 22, 'Urachiche', FALSE),
                         (459, 22, 'Yaritagua', FALSE),
                         (460, 22, 'Yumare', FALSE),
                         (461, 23, 'Bachaquero', FALSE),
                         (462, 23, 'Bobures', FALSE),
                         (463, 23, 'Cabimas', FALSE),
                         (464, 23, 'Campo Concepción', FALSE),
                         (465, 23, 'Campo Mara', FALSE),
                         (466, 23, 'Campo Rojo', FALSE),
                         (467, 23, 'Carrasquero', FALSE),
                         (468, 23, 'Casigua', FALSE),
                         (469, 23, 'Chiquinquirá', FALSE),
                         (470, 23, 'Ciudad Ojeda', FALSE),
                         (471, 23, 'El Batey', FALSE),
                         (472, 23, 'El Carmelo', FALSE),
                         (473, 23, 'El Chivo', FALSE),
                         (474, 23, 'El Guayabo', FALSE),
                         (475, 23, 'El Mene', FALSE),
                         (476, 23, 'El Venado', FALSE),
                         (477, 23, 'Encontrados', FALSE),
                         (478, 23, 'Gibraltar', FALSE),
                         (479, 23, 'Isla de Toas', FALSE),
                         (480, 23, 'La Concepción del Zulia', FALSE),
                         (481, 23, 'La Paz', FALSE),
                         (482, 23, 'La Sierrita', FALSE),
                         (483, 23, 'Lagunillas del Zulia', FALSE),
                         (484, 23, 'Las Piedras de Perijá', FALSE),
                         (485, 23, 'Los Cortijos', FALSE),
                         (486, 23, 'Machiques', FALSE),
                         (487, 23, 'Maracaibo', TRUE),
                         (488, 23, 'Mene Grande', FALSE),
                         (489, 23, 'Palmarejo', FALSE),
                         (490, 23, 'Paraguaipoa', FALSE),
                         (491, 23, 'Potrerito', FALSE),
                         (492, 23, 'Pueblo Nuevo del Zulia', FALSE),
                         (493, 23, 'Puertos de Altagracia', FALSE),
                         (494, 23, 'Punta Gorda', FALSE),
                         (495, 23, 'Sabaneta de Palma', FALSE),
                         (496, 23, 'San Francisco', FALSE),
                         (497, 23, 'San José de Perijá', FALSE),
                         (498, 23, 'San Rafael del Moján', FALSE),
                         (499, 23, 'San Timoteo', FALSE),
                         (500, 23, 'Santa Bárbara Del Zulia', FALSE),
                         (501, 23, 'Santa Cruz de Mara', FALSE),
                         (502, 23, 'Santa Cruz del Zulia', FALSE),
                         (503, 23, 'Santa Rita', FALSE),
                         (504, 23, 'Sinamaica', FALSE),
                         (505, 23, 'Tamare', FALSE),
                         (506, 23, 'Tía Juana', FALSE),
                         (507, 23, 'Villa del Rosario', FALSE),
                         (508, 21, 'La Guaira', TRUE),
                         (509, 21, 'Catia La Mar', FALSE),
                         (510, 21, 'Macuto', FALSE),
                         (511, 21, 'Naiguatá', FALSE),
                         (512, 25, 'Archipiélago Los Monjes', FALSE),
                         (513, 25, 'Isla La Tortuga y Cayos adyacentes', FALSE),
                         (514, 25, 'Isla La Sola', FALSE),
                         (515, 25, 'Islas Los Testigos', FALSE),
                         (516, 25, 'Islas Los Frailes', FALSE),
                         (517, 25, 'Isla La Orchila', FALSE),
                         (518, 25, 'Archipiélago Las Aves', FALSE),
                         (519, 25, 'Isla de Aves', FALSE),
                         (520, 25, 'Isla La Blanquilla', FALSE),
                         (521, 25, 'Isla de Patos', FALSE),
                         (522, 25, 'Islas Los Hermanos', FALSE)";

        DB::connection('shared')->unprepared($query);
    }
}
