# For more information: https://laravel.com/docs/sail
version: '3'

services:
    web:
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - postgres

    postgres:
        build: ./docker/pgsql/latest
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            POSTGRES_DB_FILE: /run/secrets/secret_db
            POSTGRES_USER_FILE: /run/secrets/secret_user
            POSTGRES_PASSWORD_FILE: /run/secrets/secret_pswd
        secrets:
            - secret_db
            - secret_user
            - secret_pswd
        volumes:
            - 'sailpgsql:/var/lib/postgresql/data'
            - ./docker/pgsql/scripts:/docker-entrypoint-initdb.d
        networks:
            - sail
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: dbadmin@studium.com
            PGADMIN_DEFAULT_PASSWORD: muy-secreto
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - '45000:80'
        networks:
            - sail
        restart: unless-stopped

networks:
    sail:
        driver: bridge

volumes:
    sailpgsql:
        driver: local
    pgadmin:
        driver: local

secrets:
    secret_db:
        file: ./secrets/secret_db.txt
    secret_user:
        file: ./secrets/secret_user.txt
    secret_pswd:
        file: ./secrets/secret_pswd.txt
